Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -119,28 +119,44 @@ generate_sbom:
     - curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
     - curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
     - |
-     if ! cat install.sh.checksum | sha256sum ; then
+      if ! cat install.sh.checksum | sha256sum ; then
       echo "install.sh checksum failed"
       exit 1
-     fi
-     BINDIR="." sh install.sh
-     rm install.sh install.sh.checksum
-    - ./billy generate /
-     --access-token $GITLAB_TOKEN /
-     --aqua-key $AQUA_KEY /
-     --aqua-secret $AQUA_SECRET /
-     --cspm-url https://stage.api.cloudsploit.com /
-     --artifact-path "$CI_PROJECT_DIR"
-     --package-json
-     --sast
-     --reachability
-    - export AQUA_KEY=$AQUA_KEY
-    - export AQUA_SECRET=$AQUA_SECRET
-    - export GITLAB_TOKEN=$GITLAB_TOKEN
-    - export AQUA_URL=https://api.dev.supply-chain.cloud.aquasec.com
-    - export CSPM_URL=https://stage.api.cloudsploit.com
-    - export TRIVY_RUN_AS_PLUGIN=aqua
-    - trivy fs --scanners config,vuln,secret .
+      fi
+      BINDIR="." sh install.sh
+      rm install.sh install.sh.checksum
+      - ./billy generate /
+      --access-token $GITLAB_TOKEN /
+      --aqua-key $AQUA_KEY /
+      --aqua-secret $AQUA_SECRET /
+      --cspm-url https://stage.api.cloudsploit.com /
+      --artifact-path "$CI_PROJECT_DIR"
+    # - export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
+    # - curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+    # - curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+    # - |
+    #  if ! cat install.sh.checksum | sha256sum ; then
+    #   echo "install.sh checksum failed"
+    #   exit 1
+    #  fi
+    #  BINDIR="." sh install.sh
+    #  rm install.sh install.sh.checksum
+    # - ./billy generate /
+    #  --access-token $GITLAB_TOKEN /
+    #  --aqua-key $AQUA_KEY /
+    #  --aqua-secret $AQUA_SECRET /
+    #  --cspm-url https://stage.api.cloudsploit.com /
+    #  --artifact-path "$CI_PROJECT_DIR"
+    #  --package-json
+    #  --sast
+    #  --reachability
+    # - export AQUA_KEY=$AQUA_KEY
+    # - export AQUA_SECRET=$AQUA_SECRET
+    # - export GITLAB_TOKEN=$GITLAB_TOKEN
+    # - export AQUA_URL=https://api.dev.supply-chain.cloud.aquasec.com
+    # - export CSPM_URL=https://stage.api.cloudsploit.com
+    # - export TRIVY_RUN_AS_PLUGIN=aqua
+    # - trivy fs --scanners config,vuln,secret .
 
   tags:
     - docker
