Update pipline variables

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,9 +10,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v2
       - name: Setup Node.js environment
-        uses: actions/setup-node@v4
+        uses: actions/setup-node@v2
         with:
           node-version: '16'
       - run: npm install
@@ -23,43 +23,49 @@ jobs:
   build_image:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v2
         with:
           persist-credentials: false
       - id: docker-login
         run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+      - name: Cache Docker layers
+        uses: actions/cache@v2
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-buildx-
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
       - name: Build and Push Docker Image
-        run: |
-          IMAGE_NAME="bakery-app"
-          docker build --label "com.aqua.security.policy=immutable" -t ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} .
-          docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
+        run: >
+          IMAGE_NAME="bakery-app" &&
+          docker buildx create --use &&
+          docker buildx build --push --tag ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache
 
   aqua_scan:
-      runs-on: ubuntu-latest
-      needs: build_image
-      env:
-        DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
-        IMAGE_NAME: "bakery-app"
-      steps:
-        - uses: actions/checkout@v3
-          with:
-            persist-credentials: false
-        - run: echo $DOCKER_AUTH_CONFIG > /home/runner/.docker/config.json
-        - id: docker-pull-scanner
-          run: docker pull registry.aquasec.com/scanner:2022.4
-        - name: Run Aqua Security Scan
-          run: |
-            IMAGE_TAG=ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
-            docker run --rm -v $(pwd)/artifacts:/artifacts --entrypoint="" registry.aquasec.com/scanner:2022.4 /opt/aquasec/scannercli scan -H ${{ secrets.AQUA_SERVER }} --token ${{ secrets.AQUA_TOKEN }} --registry "Github" $IMAGE_TAG --show-negligible --register-compliant --htmlfile /artifacts/aqua-scan.html --jsonfile /artifacts/aqua-scan.json
-        - name: Upload Aqua Reports as Artifacts
-          if: always()  # Ensures this step runs even if previous steps fail
-          uses: actions/upload-artifact@v3
-          with:
-            name: aqua-reports
-            path: artifacts/
-
-
-
+    runs-on: ubuntu-latest
+    needs: build_image
+    env:
+      DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
+      IMAGE_NAME: "bakery-app"
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          persist-credentials: false
+      - run: echo $DOCKER_AUTH_CONFIG > /home/runner/.docker/config.json
+      - id: docker-pull-scanner
+        run: docker pull registry.aquasec.com/scanner:2022.4
+      - name: Run Aqua Security Scan
+        run: |
+          IMAGE_TAG=ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
+          docker run --rm -v $(pwd)/artifacts:/artifacts --entrypoint="" registry.aquasec.com/scanner:2022.4 /opt/aquasec/scannercli scan -H ${{ secrets.AQUA_SERVER }} --token ${{ secrets.AQUA_TOKEN }} --registry "Github" $IMAGE_TAG --show-negligible --register-compliant --htmlfile /artifacts/aqua-scan.html --jsonfile /artifacts/aqua-scan.json
+      - name: Upload Aqua Reports as Artifacts
+        if: always()  # Ensures this step runs even if previous steps fail
+        uses: actions/upload-artifact@v2
+        with:
+          name: aqua-reports
+          path: artifacts/
 
   assign_task:
     runs-on: ubuntu-latest
@@ -67,9 +73,9 @@ jobs:
     if: always()  # This ensures the job runs even if aqua_scan fails
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
       - name: Setup Python
-        uses: actions/setup-python@v3
+        uses: actions/setup-python@v2
         with:
           python-version: '3.9'
       - name: Install requests
@@ -85,13 +91,13 @@ jobs:
     if: always()  # This ensures the job runs even if assign_task fails
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
       - name: Setup Python
-        uses: actions/setup-python@v3
+        uses: actions/setup-python@v2
         with:
           python-version: '3.9'
       - name: Download Aqua Reports
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v2
         with:
           name: aqua-reports
           path: artifacts/
@@ -108,56 +114,53 @@ jobs:
     container:
       image: aquasec/aqua-scanner:latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        persist-credentials: false
-    - name: Generate SBOM using Aqua
-      run: |
-        # Set Billy server URL
-        export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
-
-        # Download and verify install script
-        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-        if ! cat install.sh.checksum | sha256sum ; then
-          echo "install.sh checksum failed"
-          exit 1
-        fi
-
-        # Install Billy
-        BINDIR="." sh install.sh
-        rm install.sh install.sh.checksum
-
-        # Generate SBOM
-        ./billy generate \
-          --access-token "${{ secrets.CI_TOKEN }}" \
-          --aqua-key "${{ secrets.AQUA_KEY }}" \
-          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-          --cspm-url https://stage.api.cloudsploit.com \
-          --artifact-path "$GITHUB_WORKSPACE" \
-          --package-json \
-          --sast \
-          --reachability
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+      - name: Generate SBOM using Aqua
+        run: |
+          # Set Billy server URL
+          export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
+          # Download and verify install script
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          # Install Billy
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          # Generate SBOM
+          ./billy generate \
+            --access-token "${{ secrets.CI_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --cspm-url https://stage.api.cloudsploit.com \
+            --artifact-path "$GITHUB_WORKSPACE" \
+            --package-json \
+            --sast \
+            --reachability
 
   sign_image:
     runs-on: ubuntu-latest
     needs: generate_sbom
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: Install Cosign
-      uses: sigstore/cosign-installer@v3.1.2
-    - name: Docker Login
-      run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-    - name: Pull Docker Image
-      run: docker pull ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
-    - name: Save Cosign Private Key
-      run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
-    - name: Sign the Docker Image
-      run: |
-        IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }})
-        cosign sign --key cosign.key $IMAGE_DIGEST
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@v3.1.2
+      - name: Docker Login
+        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+      - name: Pull Docker Image
+        run: docker pull ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
+      - name: Save Cosign Private Key
+        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
+      - name: Sign the Docker Image
+        run: |
+          IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }})
+          cosign sign --key cosign.key $IMAGE_DIGEST
 
   verify_image:
     runs-on: ubuntu-latest
@@ -165,59 +168,43 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
-      # Install Cosign
       - name: Install Cosign
         run: |
           wget https://github.com/sigstore/cosign/releases/download/v1.3.0/cosign-linux-amd64
           chmod +x cosign-linux-amd64
           sudo mv cosign-linux-amd64 /usr/local/bin/cosign
-
-      # Docker Login
       - name: Docker Login
         run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-
-      # Pull the Docker Image
       - name: Pull Docker Image
         run: docker pull ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
-
-      # Save the Cosign Public Key
       - name: Save Cosign Public Key
         run: echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub
-
-      # Verify the Docker Image
       - name: Verify the Docker Image
         run: |
           IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }})
           cosign verify --key cosign.pub $IMAGE_DIGEST
 
-
-
-
   record_metadata:
-      runs-on: ubuntu-latest
-      needs: verify_image
-      container:
-        image: python:3.9
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v3
-
-        - name: Generate Timestamp and Signature Placeholder
-          run: |
-            date +%s > timestamp_file.txt
-            echo "PlaceholderSignature" > signature_file.txt  # This will act as a placeholder
-
-        - name: Run Python Script to Generate Metadata
-          run: python3 ci_scripts/generate_metadata_artifact.py signature_file.txt timestamp_file.txt metadata_artifact  # Added signature_file.txt as a placeholder
-
-        - name: Upload Metadata Artifact
-          uses: actions/upload-artifact@v3
-          with:
-            name: metadata-artifact
-            path: |
-              metadata_artifact.json
-              metadata_artifact.html
+    runs-on: ubuntu-latest
+    needs: verify_image
+    container:
+      image: python:3.9
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Generate Timestamp and Signature Placeholder
+        run: |
+          date +%s > timestamp_file.txt
+          echo "PlaceholderSignature" > signature_file.txt  # This will act as a placeholder
+      - name: Run Python Script to Generate Metadata
+        run: python3 ci_scripts/generate_metadata_artifact.py signature_file.txt timestamp_file.txt metadata_artifact  # Added signature_file.txt as a placeholder
+      - name: Upload Metadata Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: metadata-artifact
+          path: |
+            metadata_artifact.json
+            metadata_artifact.html
 
 
   publish_to_gh_pages:
