added SBOM manifest

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,30 +46,42 @@ jobs:
         IMAGE_TAG=ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
         docker run --rm -v $(pwd)/artifacts:/artifacts --entrypoint="" registry.aquasec.com/scanner:2022.4 /opt/aquasec/scannercli scan -H ${{ secrets.AQUA_SERVER }} --token ${{ secrets.AQUA_TOKEN }} --registry "Github" $IMAGE_TAG --show-negligible --register-compliant --htmlfile /artifacts/aqua-scan.html >/dev/null
 
-  aqua_sbom:
-      runs-on: ubuntu-latest
-      needs: build_image
-      container:
-        image: aquasec/aqua-scanner:latest
-      steps:
+  generate_sbom:
+    runs-on: ubuntu-latest
+    needs: [aqua_scan]
+    container:
+      image: aquasec/aqua-scanner:latest
+    steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Generate SBOM with Billy
+      - name: Generate SBOM using Aqua
         run: |
           export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
           curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          sh install.sh
-          ./billy generate \
-            --access-token "${{ secrets.CI_TOKEN }}" \
-            --aqua-key "${{ secrets.AQUA_KEY }}" \
-            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate / \
+            --access-token ${{ secrets.GITHUB_TOKEN }} \
+            --aqua-key ${{ secrets.AQUA_KEY }} \
+            --aqua-secret ${{ secrets.AQUA_SECRET }} \
             --cspm-url https://stage.api.cloudsploit.com \
-            --artifact-path "ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}"
-        env:
-          AQUA_KEY: ${{ secrets.AQUA_KEY }}
-          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-          CI_TOKEN: ${{ secrets.CI_TOKEN }}
+            --artifact-path "$GITHUB_WORKSPACE" \
+            --package-json \
+            --sast \
+            --reachability
+          export AQUA_KEY=${{ secrets.AQUA_KEY }}
+          export AQUA_SECRET=${{ secrets.AQUA_SECRET }}
+          export AQUA_URL=https://api.dev.supply-chain.cloud.aquasec.com
+          export CSPM_URL=https://stage.api.cloudsploit.com
+          export TRIVY_RUN_AS_PLUGIN=aqua
+          trivy fs --scanners config,vuln,secret .
+
 
 
 
