added cosign job

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,8 +32,6 @@ jobs:
         docker build --label "com.aqua.security.policy=immutable" -t ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} .
         docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
 
-
-
   aqua_scan:
     runs-on: ubuntu-latest
     needs: build_image
@@ -51,78 +49,61 @@ jobs:
         docker run --rm -v $(pwd)/artifacts:/artifacts --entrypoint="" registry.aquasec.com/scanner:2022.4 /opt/aquasec/scannercli scan -H ${{ secrets.AQUA_SERVER }} --token ${{ secrets.AQUA_TOKEN }} --registry "Github" $IMAGE_TAG --show-negligible --register-compliant --htmlfile /artifacts/aqua-scan.html >/dev/null
 
   generate_sbom:
-      runs-on: ubuntu-latest
-      needs: [aqua_scan]
-      container:
-        image: aquasec/aqua-scanner:latest
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v2
+    runs-on: ubuntu-latest
+    needs: [aqua_scan]
+    container:
+      image: aquasec/aqua-scanner:latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    - name: Generate SBOM using Aqua
+      run: |
+        # Set Billy server URL
+        export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
 
-        - name: Generate SBOM using Aqua
-          run: |
-            # Set Billy server URL
-            export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
+        # Download and verify install script
+        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+        if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+        fi
 
-            # Download and verify install script
-            curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-            curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-            if ! cat install.sh.checksum | sha256sum ; then
-              echo "install.sh checksum failed"
-              exit 1
-            fi
+        # Install Billy
+        BINDIR="." sh install.sh
+        rm install.sh install.sh.checksum
 
-            # Install Billy
-            BINDIR="." sh install.sh
-            rm install.sh install.sh.checksum
-
-            # Generate SBOM
-            ./billy generate \
-              --access-token "${{ secrets.GITHUB_TOKEN }}" \
-              --aqua-key "${{ secrets.AQUA_KEY }}" \
-              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-              --cspm-url https://stage.api.cloudsploit.com \
-              --artifact-path "$GITHUB_WORKSPACE" \
-              --package-json \
-              --sast \
-              --reachability
-
-        - name: Run Trivy Scan
-          run: |
-            # Set environment variables
-            export AQUA_KEY=${{ secrets.AQUA_KEY }}
-            export AQUA_SECRET=${{ secrets.AQUA_SECRET }}
-            export AQUA_URL=https://api.dev.supply-chain.cloud.aquasec.com
-            export CSPM_URL=https://stage.api.cloudsploit.com
-            export TRIVY_RUN_AS_PLUGIN=aqua
-
-            # Run Trivy file system scanner
-            trivy fs --scanners config,vuln,secret .
+        # Generate SBOM
+        ./billy generate \
+          --access-token "${{ secrets.GITHUB_TOKEN }}" \
+          --aqua-key "${{ secrets.AQUA_KEY }}" \
+          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+          --cspm-url https://stage.api.cloudsploit.com \
+          --artifact-path "$GITHUB_WORKSPACE" \
+          --package-json \
+          --sast \
+          --reachability
 
   sign_image:
-      runs-on: ubuntu-latest
-      needs: build_image
-      steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Install Cosign
-        uses: sigstore/cosign-installer@v3.1.2
-      - name: Sign the Docker Image
-        run: |
-          cosign sign -key ${{ secrets.COSIGN_PRIVATE_KEY }} ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
+    runs-on: ubuntu-latest
+    needs: build_image # depends on the build_image job
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    - name: Install Cosign
+      uses: sigstore/cosign-installer@v3.1.2
+    - name: Sign the Docker Image
+      run: |
+        cosign sign -key ${{ secrets.COSIGN_PRIVATE_KEY }} ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
 
-    verify_image:
-      runs-on: ubuntu-latest
-      needs: sign_image
-      steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Install Cosign
-        uses: sigstore/cosign-installer@v3.1.2
-      - name: Verify the Docker Image
-        run: |
-          cosign verify -key cosign.pub ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
-
-
-
-
+  verify_image:
+    runs-on: ubuntu-latest
+    needs: sign_image # depends on the sign_image job
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    - name: Install Cosign
+      uses: sigstore/cosign-installer@v3.1.2
+    - name: Verify the Docker Image
+      run: |
+        cosign verify -key cosign.pub ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
