added SBOM manifest

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,7 +14,7 @@ jobs:
     - name: Use Node.js
       uses: actions/setup-node@v2
       with:
-        node-version: '14'
+        node-version: '16'
     - name: Install dependencies
       run: npm install
       working-directory: ./app
@@ -54,40 +54,50 @@ jobs:
         docker run --rm -v $(pwd)/artifacts:/artifacts --entrypoint="" registry.aquasec.com/scanner:2022.4 /opt/aquasec/scannercli scan -H ${{ secrets.AQUA_SERVER }} --token ${{ secrets.AQUA_TOKEN }} --registry "Github" $IMAGE_TAG --show-negligible --register-compliant --htmlfile /artifacts/aqua-scan.html >/dev/null
 
   aqua_sbom:
-      runs-on: ubuntu-latest
-      needs: build_image
-      steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Docker Login to GHCR
-        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-      - name: Run Aqua SBOM and Code Scan
-        run: |
-          export IMAGE_NAME="bakery-app"
-          export IMAGE_TAG=ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
-          docker pull $IMAGE_TAG  # Make sure the image exists
-          export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
-          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | sha256sum ; then
-            echo "install.sh checksum failed"
-            exit 1
-          fi
-          BINDIR="." sh install.sh
-          rm install.sh install.sh.checksum
-          ./billy generate \
-            --access-token ${{ secrets.CI_TOKEN }} \
-            --aqua-key ${{ secrets.AQUA_KEY }} \
-            --aqua-secret ${{ secrets.AQUA_SECRET }} \
-            --cspm-url https://stage.api.cloudsploit.com \
-            --artifact-path "$IMAGE_TAG"
-          trivy fs --scanners config,vuln,secret .
-        env:
-          AQUA_KEY: ${{ secrets.AQUA_KEY }}
-          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
-          AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com
-          CSPM_URL: https://stage.api.cloudsploit.com
-          TRIVY_RUN_AS_PLUGIN: 'aqua'
+    runs-on: ubuntu-latest
+    needs: build_image
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Docker Login to GHCR
+      run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+    - name: Pull Docker Image
+      run: |
+        export IMAGE_NAME="bakery-app"
+        docker pull ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
+
+    - name: Install Trivy
+      run: |
+        wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
+        sudo dpkg -i trivy_0.19.2_Linux-64bit.deb
+
+    - name: Run Aqua SBOM and Code Scan
+      run: |
+        export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
+        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+        if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+        fi
+        BINDIR="." sh install.sh
+        rm install.sh install.sh.checksum
+        ./billy generate \
+          --access-token "${{ secrets.CI_TOKEN }}" \
+          --aqua-key "${{ secrets.AQUA_KEY }}" \
+          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+          --cspm-url https://stage.api.cloudsploit.com \
+          --artifact-path "ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}"
+        trivy fs --scanners config,vuln,secret .
+      env:
+        AQUA_KEY: ${{ secrets.AQUA_KEY }}
+        AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
+        AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com
+        CSPM_URL: https://stage.api.cloudsploit.com
+        TRIVY_RUN_AS_PLUGIN: 'aqua'
+
 
 
