added SBOM manifest

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,35 +48,36 @@ jobs:
 
   aqua_sbom:
     runs-on: ubuntu-latest
-    needs: build_image
+    needs: [aqua_scan]
+    container:
+      image: aquasec/aqua-scanner:latest
     steps:
-    - uses: actions/checkout@v2
-    - id: debug-image-path
-      run: echo "Debug: Image path is ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}"
-    - id: docker-login
-      run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-    - name: Pull Docker Image
-      run: |
-        docker pull ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}
-    - name: Run Aqua SBOM and Code Scan
-      run: |
-        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-        if ! cat install.sh.checksum | sha256sum -c - ; then
-          echo "install.sh checksum failed"
-          exit 1
-        fi
-        sh install.sh
-        rm install.sh install.sh.checksum
-        ./billy generate \
-         --access-token "${{ secrets.CI_TOKEN }}" \
-         --aqua-key "${{ secrets.AQUA_KEY }}" \
-         --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-         --cspm-url https://stage.api.cloudsploit.com \
-         --artifact-path "ghcr.io/${{ github.repository }}/bakery-app:${{ github.sha }}"
-      env:
-        AQUA_KEY: ${{ secrets.AQUA_KEY }}
-        AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-        CI_TOKEN: ${{ secrets.CI_TOKEN }}
-        AQUA_URL: https://api.dev.supply-chain.cloud.aquasec.com
-        CSPM_URL: https://stage.api.cloudsploit.com
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Generate SBOM using Aqua
+        run: |
+          export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate / \
+            --access-token ${{ secrets.GITHUB_TOKEN }} \
+            --aqua-key ${{ secrets.AQUA_KEY }} \
+            --aqua-secret ${{ secrets.AQUA_SECRET }} \
+            --cspm-url https://stage.api.cloudsploit.com \
+            --artifact-path "$GITHUB_WORKSPACE" \
+            --package-json \
+            --sast \
+            --reachability
+          export AQUA_KEY=${{ secrets.AQUA_KEY }}
+          export AQUA_SECRET=${{ secrets.AQUA_SECRET }}
+          export AQUA_URL=https://api.dev.supply-chain.cloud.aquasec.com
+          export CSPM_URL=https://stage.api.cloudsploit.com
+          export TRIVY_RUN_AS_PLUGIN=aqua
+          trivy fs --scanners config,vuln,secret .
